pipeline {
    agent {
        label 'Agent - 1'
    }
    options {
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    // parameters{
    //     choice(name: 'CHOICE', choices: ['plan','apply','destroy'], description: 'Pick something')
    // }
    environment {
        def version = ' '
    }
    stages {
        stage('init') {
            steps {
                dir('Backend'){
                sh """ ls -ltr """
                } 
            }
        }
        stage('Version') {
            steps {
                script {
                    def packageJson = readFile('package.json')
                    def packageData = readJSON text: packageJson
                    version = packageData.version
                    echo "Application Version = $version"
                }
            }
        }
        // stage('Deploy'){
        //     steps {

        //     }
        // }
        // stage('Destroy') {
        //     steps {

        //     }
        // }
    }

    post { 
        always { 
            echo 'I will always say Hello again!'
            // deleteDir()
        }
        success { 
            echo 'I will run when pipeline is success'
        }
        failure { 
            echo 'I will run when pipeline is failure'
        }

    }
    
}
