pipeline {
    agent {
        label 'Agent - 1'
    }
    options {
        timeout(time: 1, unit: 'HOURS')
        disableConcurrentBuilds()
        ansiColor('xterm') 
    }
    parameters {
        string(name: 'version', defaultValue: '1.1.0', description:'What is the Application Version' )
    }
    stages {
        stage('Version') {
            steps {
                echo "Application Version: ${params.version}"
            }
        }
        stage('Init') {
            steps {
                sh """
                pwd
                ls -ltr
                cd backend-deploy
                ls -ltr
                """
            }    
        }
        stage('Deploy') {
            steps {
                sh 'echo Hello World, from Deploy'
            }
        }
    }

    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'I will run when pipeline is success'
        }
        failure { 
            echo 'I will run when pipeline is failure'
        }

        }
    
    }

